import { Middleware, applyMiddleware, compose, createStore, Store } from 'redux'
import enhancedThunk from 'redux-thunk'
import throttle from 'lodash/throttle'
import { rootReducer, initialState } from 'reducers/'
import { State, Action, ActionType } from 'types/'
